name: Compile Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run compile script
      run: |
        bash compile_script.sh
      continue-on-error: true

    - name: Check if compilation successful
      run: |
        if [ $? -eq 0 ]; then
          echo "Compilation successful."
        else
          echo "Compilation failed."
          exit 1
        fi